# Generated by Django 5.0.3 on 2024-04-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_producte', models.CharField(max_length=50)),
                ('preu', models.DecimalField(decimal_places=2, max_digits=5)),
                ('origen', models.CharField(max_length=50)),
                ('pes_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock', models.IntegerField()),
                ('tipus', models.CharField(choices=[('C', 'Carnics'), ('L', 'Làctics'), ('P', 'Peixos'), ('V', 'Verdures'), ('H', 'Hortalises'), ('F', 'Fruita'), ('FS', 'Fruits secs')], max_length=50)),
            ],
        ),
    ]
