# Generated by Django 5.0.3 on 2024-04-17 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cataleg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cataleg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cataleg.productos')),
            ],
        ),
    ]
