# Generated by Django 5.0.3 on 2024-04-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cataleg', '0002_cataleg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Productes',
        ),
    ]
