# Generated by Django 5.0.3 on 2024-04-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cataleg', '0003_rename_productos_productes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productes',
            old_name='tipus',
            new_name='tipus_producte',
        ),
    ]
