# Generated by Django 5.0.3 on 2024-05-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagaments', '0002_remove_pagaments_caducitat_remove_pagaments_ccv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagaments',
            old_name='Carreto',
            new_name='carreto',
        ),
    ]
