# Generated by Django 5.0.3 on 2024-04-19 15:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0001_initial'),
        ('cataleg', '0004_rename_tipus_productes_tipus_producte'),
        ('pagaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='carreto',
            name='id_producto',
        ),
        migrations.RemoveField(
            model_name='carreto',
            name='importe',
        ),
        migrations.RemoveField(
            model_name='carreto',
            name='metodo_pago',
        ),
        migrations.AddField(
            model_name='carreto',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='carreto',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pagaments.usuari'),
        ),
        migrations.CreateModel(
            name='ProductoEnCarreto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('importe', models.DecimalField(decimal_places=3, max_digits=5)),
                ('metodo_pago', models.CharField(choices=[('paypal', 'paypal'), ('tarjeta', 'tarjeta'), ('transferencia', 'transferencia')], max_length=30)),
                ('id_carreto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreto.carreto')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cataleg.productes')),
            ],
        ),
    ]
