# Generated by Django 5.0.3 on 2024-04-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0003_carreto_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoencarreto',
            name='importe',
        ),
        migrations.AddField(
            model_name='carreto',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
