# Generated by Django 5.0.3 on 2024-05-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0004_remove_productoencarreto_importe_carreto_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoencarreto',
            name='metodo_pago',
        ),
        migrations.AddField(
            model_name='carreto',
            name='metodo_pago',
            field=models.CharField(choices=[('paypal', 'paypal'), ('tarjeta', 'tarjeta'), ('transferencia', 'transferencia')], default='tarjeta', max_length=30),
        ),
        migrations.AddField(
            model_name='carreto',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
