# Generated by Django 5.0.3 on 2024-05-05 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0006_alter_carreto_id_user'),
        ('pagaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreto',
            name='id_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='pagaments.usuari'),
        ),
    ]
