# Generated by Django 5.0.3 on 2024-05-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0007_alter_carreto_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreto',
            name='id_user',
        ),
    ]
