# Generated by Django 5.0.3 on 2024-05-08 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0008_remove_carreto_metodo_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carreto',
            name='id_user',
        ),
    ]
