# Generated by Django 5.0.3 on 2024-05-15 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0008_remove_carreto_id_user'),
        ('carreto', '0009_remove_carreto_id_user'),
    ]

    operations = [
    ]
