# Generated by Django 5.0.3 on 2024-04-19 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carreto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comandes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagada', models.BooleanField()),
                ('id_carreto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreto.carreto')),
            ],
        ),
    ]
