# Generated by Django 5.0.3 on 2024-05-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0006_alter_carreto_id_user'),
        ('comandes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comandes',
            name='id_carreto',
        ),
        migrations.RemoveField(
            model_name='comandes',
            name='pagada',
        ),
        migrations.AddField(
            model_name='comandes',
            name='carretos',
            field=models.ManyToManyField(to='carreto.carreto'),
        ),
    ]
