# Generated by Django 5.0.3 on 2024-05-05 17:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0006_alter_carreto_id_user'),
        ('comandes', '0002_remove_comandes_id_carreto_remove_comandes_pagada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comandes',
            name='carretos',
        ),
        migrations.AddField(
            model_name='comandes',
            name='fecha_creacion_comanda',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='CarretoEnComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carreto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreto.carreto')),
                ('id_comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comandes.comandes')),
            ],
        ),
        migrations.AddField(
            model_name='comandes',
            name='carritos',
            field=models.ManyToManyField(through='comandes.CarretoEnComanda', to='carreto.carreto'),
        ),
    ]
