# Generated by Django 5.0.3 on 2024-05-05 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreto', '0007_alter_carreto_id_user'),
        ('comandes', '0003_remove_comandes_carretos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carretoencomanda',
            name='id_carreto',
        ),
        migrations.RemoveField(
            model_name='carretoencomanda',
            name='id_comanda',
        ),
        migrations.AddField(
            model_name='carretoencomanda',
            name='carreto',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='carreto.carreto'),
        ),
        migrations.AddField(
            model_name='carretoencomanda',
            name='comanda',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='comandes.comandes'),
        ),
    ]
